version: '3.1'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3310:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pontoapi

#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8000:80

volumes:
  database: